/*
FastReport Cloud

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gofrcloud

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GroupUserVM type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GroupUserVM{}

// GroupUserVM struct for GroupUserVM
type GroupUserVM struct {
	CloudBaseVM
	UserId NullableString `json:"userId,omitempty"`
	T string `json:"$t"`
}

type _GroupUserVM GroupUserVM

// NewGroupUserVM instantiates a new GroupUserVM object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGroupUserVM(t string) *GroupUserVM {
	this := GroupUserVM{}
	this.T = t
	return &this
}

// NewGroupUserVMWithDefaults instantiates a new GroupUserVM object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGroupUserVMWithDefaults() *GroupUserVM {
	this := GroupUserVM{}
	return &this
}

// GetUserId returns the UserId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GroupUserVM) GetUserId() string {
	if o == nil || IsNil(o.UserId.Get()) {
		var ret string
		return ret
	}
	return *o.UserId.Get()
}

// GetUserIdOk returns a tuple with the UserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GroupUserVM) GetUserIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.UserId.Get(), o.UserId.IsSet()
}

// HasUserId returns a boolean if a field has been set.
func (o *GroupUserVM) HasUserId() bool {
	if o != nil && o.UserId.IsSet() {
		return true
	}

	return false
}

// SetUserId gets a reference to the given NullableString and assigns it to the UserId field.
func (o *GroupUserVM) SetUserId(v string) {
	o.UserId.Set(&v)
}
// SetUserIdNil sets the value for UserId to be an explicit nil
func (o *GroupUserVM) SetUserIdNil() {
	o.UserId.Set(nil)
}

// UnsetUserId ensures that no value is present for UserId, not even an explicit nil
func (o *GroupUserVM) UnsetUserId() {
	o.UserId.Unset()
}

// GetT returns the T field value
func (o *GroupUserVM) GetT() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.T
}

// GetTOk returns a tuple with the T field value
// and a boolean to check if the value has been set.
func (o *GroupUserVM) GetTOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.T, true
}

// SetT sets field value
func (o *GroupUserVM) SetT(v string) {
	o.T = v
}

func (o GroupUserVM) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GroupUserVM) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	serializedCloudBaseVM, errCloudBaseVM := json.Marshal(o.CloudBaseVM)
	if errCloudBaseVM != nil {
		return map[string]interface{}{}, errCloudBaseVM
	}
	errCloudBaseVM = json.Unmarshal([]byte(serializedCloudBaseVM), &toSerialize)
	if errCloudBaseVM != nil {
		return map[string]interface{}{}, errCloudBaseVM
	}
	if o.UserId.IsSet() {
		toSerialize["userId"] = o.UserId.Get()
	}
	toSerialize["$t"] = o.T
	return toSerialize, nil
}

func (o *GroupUserVM) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"$t",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGroupUserVM := _GroupUserVM{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGroupUserVM)

	if err != nil {
		return err
	}

	*o = GroupUserVM(varGroupUserVM)

	return err
}

type NullableGroupUserVM struct {
	value *GroupUserVM
	isSet bool
}

func (v NullableGroupUserVM) Get() *GroupUserVM {
	return v.value
}

func (v *NullableGroupUserVM) Set(val *GroupUserVM) {
	v.value = val
	v.isSet = true
}

func (v NullableGroupUserVM) IsSet() bool {
	return v.isSet
}

func (v *NullableGroupUserVM) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGroupUserVM(val *GroupUserVM) *NullableGroupUserVM {
	return &NullableGroupUserVM{value: val, isSet: true}
}

func (v NullableGroupUserVM) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGroupUserVM) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


