/*
 * FastReport Cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gofrcloud

import (
	"encoding/json"
	"fmt"
)

// SubscriptionUpdate the model 'SubscriptionUpdate'
type SubscriptionUpdate int32

// List of SubscriptionUpdate
const (
	_0 SubscriptionUpdate = 0
	_1 SubscriptionUpdate = 1
	_4 SubscriptionUpdate = 4
	_8 SubscriptionUpdate = 8
	_MINUS_1 SubscriptionUpdate = -1
)

var allowedSubscriptionUpdateEnumValues = []SubscriptionUpdate{
	0,
	1,
	4,
	8,
	-1,
}

func (v *SubscriptionUpdate) UnmarshalJSON(src []byte) error {
	var value int32
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := SubscriptionUpdate(value)
	for _, existing := range allowedSubscriptionUpdateEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid SubscriptionUpdate", value)
}

// NewSubscriptionUpdateFromValue returns a pointer to a valid SubscriptionUpdate
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewSubscriptionUpdateFromValue(v int32) (*SubscriptionUpdate, error) {
	ev := SubscriptionUpdate(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for SubscriptionUpdate: valid values are %v", v, allowedSubscriptionUpdateEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v SubscriptionUpdate) IsValid() bool {
	for _, existing := range allowedSubscriptionUpdateEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to SubscriptionUpdate value
func (v SubscriptionUpdate) Ptr() *SubscriptionUpdate {
	return &v
}

type NullableSubscriptionUpdate struct {
	value *SubscriptionUpdate
	isSet bool
}

func (v NullableSubscriptionUpdate) Get() *SubscriptionUpdate {
	return v.value
}

func (v *NullableSubscriptionUpdate) Set(val *SubscriptionUpdate) {
	v.value = val
	v.isSet = true
}

func (v NullableSubscriptionUpdate) IsSet() bool {
	return v.isSet
}

func (v *NullableSubscriptionUpdate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSubscriptionUpdate(val *SubscriptionUpdate) *NullableSubscriptionUpdate {
	return &NullableSubscriptionUpdate{value: val, isSet: true}
}

func (v NullableSubscriptionUpdate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSubscriptionUpdate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

