/*
FastReport Cloud

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gofrcloud

import (
	"encoding/json"
)

// checks if the CreateContactGroupVM type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateContactGroupVM{}

// CreateContactGroupVM struct for CreateContactGroupVM
type CreateContactGroupVM struct {
	Name string `json:"name"`
	SubscriptionId NullableString `json:"subscriptionId,omitempty"`
}

// NewCreateContactGroupVM instantiates a new CreateContactGroupVM object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateContactGroupVM(name string) *CreateContactGroupVM {
	this := CreateContactGroupVM{}
	this.Name = name
	return &this
}

// NewCreateContactGroupVMWithDefaults instantiates a new CreateContactGroupVM object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateContactGroupVMWithDefaults() *CreateContactGroupVM {
	this := CreateContactGroupVM{}
	return &this
}

// GetName returns the Name field value
func (o *CreateContactGroupVM) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateContactGroupVM) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateContactGroupVM) SetName(v string) {
	o.Name = v
}

// GetSubscriptionId returns the SubscriptionId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateContactGroupVM) GetSubscriptionId() string {
	if o == nil || IsNil(o.SubscriptionId.Get()) {
		var ret string
		return ret
	}
	return *o.SubscriptionId.Get()
}

// GetSubscriptionIdOk returns a tuple with the SubscriptionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateContactGroupVM) GetSubscriptionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SubscriptionId.Get(), o.SubscriptionId.IsSet()
}

// HasSubscriptionId returns a boolean if a field has been set.
func (o *CreateContactGroupVM) HasSubscriptionId() bool {
	if o != nil && o.SubscriptionId.IsSet() {
		return true
	}

	return false
}

// SetSubscriptionId gets a reference to the given NullableString and assigns it to the SubscriptionId field.
func (o *CreateContactGroupVM) SetSubscriptionId(v string) {
	o.SubscriptionId.Set(&v)
}
// SetSubscriptionIdNil sets the value for SubscriptionId to be an explicit nil
func (o *CreateContactGroupVM) SetSubscriptionIdNil() {
	o.SubscriptionId.Set(nil)
}

// UnsetSubscriptionId ensures that no value is present for SubscriptionId, not even an explicit nil
func (o *CreateContactGroupVM) UnsetSubscriptionId() {
	o.SubscriptionId.Unset()
}

func (o CreateContactGroupVM) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateContactGroupVM) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if o.SubscriptionId.IsSet() {
		toSerialize["subscriptionId"] = o.SubscriptionId.Get()
	}
	return toSerialize, nil
}

type NullableCreateContactGroupVM struct {
	value *CreateContactGroupVM
	isSet bool
}

func (v NullableCreateContactGroupVM) Get() *CreateContactGroupVM {
	return v.value
}

func (v *NullableCreateContactGroupVM) Set(val *CreateContactGroupVM) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateContactGroupVM) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateContactGroupVM) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateContactGroupVM(val *CreateContactGroupVM) *NullableCreateContactGroupVM {
	return &NullableCreateContactGroupVM{value: val, isSet: true}
}

func (v NullableCreateContactGroupVM) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateContactGroupVM) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


