/*
FastReport Cloud

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gofrcloud

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the FileStatusVM type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FileStatusVM{}

// FileStatusVM struct for FileStatusVM
type FileStatusVM struct {
	CloudBaseVM
	FileStatus *FileStatus `json:"fileStatus,omitempty"`
	T string `json:"$t"`
}

type _FileStatusVM FileStatusVM

// NewFileStatusVM instantiates a new FileStatusVM object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFileStatusVM(t string) *FileStatusVM {
	this := FileStatusVM{}
	this.T = t
	return &this
}

// NewFileStatusVMWithDefaults instantiates a new FileStatusVM object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFileStatusVMWithDefaults() *FileStatusVM {
	this := FileStatusVM{}
	return &this
}

// GetFileStatus returns the FileStatus field value if set, zero value otherwise.
func (o *FileStatusVM) GetFileStatus() FileStatus {
	if o == nil || IsNil(o.FileStatus) {
		var ret FileStatus
		return ret
	}
	return *o.FileStatus
}

// GetFileStatusOk returns a tuple with the FileStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileStatusVM) GetFileStatusOk() (*FileStatus, bool) {
	if o == nil || IsNil(o.FileStatus) {
		return nil, false
	}
	return o.FileStatus, true
}

// HasFileStatus returns a boolean if a field has been set.
func (o *FileStatusVM) HasFileStatus() bool {
	if o != nil && !IsNil(o.FileStatus) {
		return true
	}

	return false
}

// SetFileStatus gets a reference to the given FileStatus and assigns it to the FileStatus field.
func (o *FileStatusVM) SetFileStatus(v FileStatus) {
	o.FileStatus = &v
}

// GetT returns the T field value
func (o *FileStatusVM) GetT() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.T
}

// GetTOk returns a tuple with the T field value
// and a boolean to check if the value has been set.
func (o *FileStatusVM) GetTOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.T, true
}

// SetT sets field value
func (o *FileStatusVM) SetT(v string) {
	o.T = v
}

func (o FileStatusVM) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FileStatusVM) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	serializedCloudBaseVM, errCloudBaseVM := json.Marshal(o.CloudBaseVM)
	if errCloudBaseVM != nil {
		return map[string]interface{}{}, errCloudBaseVM
	}
	errCloudBaseVM = json.Unmarshal([]byte(serializedCloudBaseVM), &toSerialize)
	if errCloudBaseVM != nil {
		return map[string]interface{}{}, errCloudBaseVM
	}
	if !IsNil(o.FileStatus) {
		toSerialize["fileStatus"] = o.FileStatus
	}
	toSerialize["$t"] = o.T
	return toSerialize, nil
}

func (o *FileStatusVM) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"$t",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFileStatusVM := _FileStatusVM{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varFileStatusVM)

	if err != nil {
		return err
	}

	*o = FileStatusVM(varFileStatusVM)

	return err
}

type NullableFileStatusVM struct {
	value *FileStatusVM
	isSet bool
}

func (v NullableFileStatusVM) Get() *FileStatusVM {
	return v.value
}

func (v *NullableFileStatusVM) Set(val *FileStatusVM) {
	v.value = val
	v.isSet = true
}

func (v NullableFileStatusVM) IsSet() bool {
	return v.isSet
}

func (v *NullableFileStatusVM) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFileStatusVM(val *FileStatusVM) *NullableFileStatusVM {
	return &NullableFileStatusVM{value: val, isSet: true}
}

func (v NullableFileStatusVM) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFileStatusVM) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


