/*
FastReport Cloud

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gofrcloud

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DataSourcesVM type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DataSourcesVM{}

// DataSourcesVM struct for DataSourcesVM
type DataSourcesVM struct {
	CloudBaseVM
	DataSources []DataSourceVM `json:"dataSources,omitempty"`
	Count *int64 `json:"count,omitempty"`
	Skip *int32 `json:"skip,omitempty"`
	Take *int32 `json:"take,omitempty"`
	T string `json:"$t"`
}

type _DataSourcesVM DataSourcesVM

// NewDataSourcesVM instantiates a new DataSourcesVM object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDataSourcesVM(t string) *DataSourcesVM {
	this := DataSourcesVM{}
	this.T = t
	return &this
}

// NewDataSourcesVMWithDefaults instantiates a new DataSourcesVM object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDataSourcesVMWithDefaults() *DataSourcesVM {
	this := DataSourcesVM{}
	return &this
}

// GetDataSources returns the DataSources field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DataSourcesVM) GetDataSources() []DataSourceVM {
	if o == nil {
		var ret []DataSourceVM
		return ret
	}
	return o.DataSources
}

// GetDataSourcesOk returns a tuple with the DataSources field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DataSourcesVM) GetDataSourcesOk() ([]DataSourceVM, bool) {
	if o == nil || IsNil(o.DataSources) {
		return nil, false
	}
	return o.DataSources, true
}

// HasDataSources returns a boolean if a field has been set.
func (o *DataSourcesVM) HasDataSources() bool {
	if o != nil && IsNil(o.DataSources) {
		return true
	}

	return false
}

// SetDataSources gets a reference to the given []DataSourceVM and assigns it to the DataSources field.
func (o *DataSourcesVM) SetDataSources(v []DataSourceVM) {
	o.DataSources = v
}

// GetCount returns the Count field value if set, zero value otherwise.
func (o *DataSourcesVM) GetCount() int64 {
	if o == nil || IsNil(o.Count) {
		var ret int64
		return ret
	}
	return *o.Count
}

// GetCountOk returns a tuple with the Count field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DataSourcesVM) GetCountOk() (*int64, bool) {
	if o == nil || IsNil(o.Count) {
		return nil, false
	}
	return o.Count, true
}

// HasCount returns a boolean if a field has been set.
func (o *DataSourcesVM) HasCount() bool {
	if o != nil && !IsNil(o.Count) {
		return true
	}

	return false
}

// SetCount gets a reference to the given int64 and assigns it to the Count field.
func (o *DataSourcesVM) SetCount(v int64) {
	o.Count = &v
}

// GetSkip returns the Skip field value if set, zero value otherwise.
func (o *DataSourcesVM) GetSkip() int32 {
	if o == nil || IsNil(o.Skip) {
		var ret int32
		return ret
	}
	return *o.Skip
}

// GetSkipOk returns a tuple with the Skip field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DataSourcesVM) GetSkipOk() (*int32, bool) {
	if o == nil || IsNil(o.Skip) {
		return nil, false
	}
	return o.Skip, true
}

// HasSkip returns a boolean if a field has been set.
func (o *DataSourcesVM) HasSkip() bool {
	if o != nil && !IsNil(o.Skip) {
		return true
	}

	return false
}

// SetSkip gets a reference to the given int32 and assigns it to the Skip field.
func (o *DataSourcesVM) SetSkip(v int32) {
	o.Skip = &v
}

// GetTake returns the Take field value if set, zero value otherwise.
func (o *DataSourcesVM) GetTake() int32 {
	if o == nil || IsNil(o.Take) {
		var ret int32
		return ret
	}
	return *o.Take
}

// GetTakeOk returns a tuple with the Take field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DataSourcesVM) GetTakeOk() (*int32, bool) {
	if o == nil || IsNil(o.Take) {
		return nil, false
	}
	return o.Take, true
}

// HasTake returns a boolean if a field has been set.
func (o *DataSourcesVM) HasTake() bool {
	if o != nil && !IsNil(o.Take) {
		return true
	}

	return false
}

// SetTake gets a reference to the given int32 and assigns it to the Take field.
func (o *DataSourcesVM) SetTake(v int32) {
	o.Take = &v
}

// GetT returns the T field value
func (o *DataSourcesVM) GetT() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.T
}

// GetTOk returns a tuple with the T field value
// and a boolean to check if the value has been set.
func (o *DataSourcesVM) GetTOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.T, true
}

// SetT sets field value
func (o *DataSourcesVM) SetT(v string) {
	o.T = v
}

func (o DataSourcesVM) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DataSourcesVM) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	serializedCloudBaseVM, errCloudBaseVM := json.Marshal(o.CloudBaseVM)
	if errCloudBaseVM != nil {
		return map[string]interface{}{}, errCloudBaseVM
	}
	errCloudBaseVM = json.Unmarshal([]byte(serializedCloudBaseVM), &toSerialize)
	if errCloudBaseVM != nil {
		return map[string]interface{}{}, errCloudBaseVM
	}
	if o.DataSources != nil {
		toSerialize["dataSources"] = o.DataSources
	}
	if !IsNil(o.Count) {
		toSerialize["count"] = o.Count
	}
	if !IsNil(o.Skip) {
		toSerialize["skip"] = o.Skip
	}
	if !IsNil(o.Take) {
		toSerialize["take"] = o.Take
	}
	toSerialize["$t"] = o.T
	return toSerialize, nil
}

func (o *DataSourcesVM) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"$t",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDataSourcesVM := _DataSourcesVM{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDataSourcesVM)

	if err != nil {
		return err
	}

	*o = DataSourcesVM(varDataSourcesVM)

	return err
}

type NullableDataSourcesVM struct {
	value *DataSourcesVM
	isSet bool
}

func (v NullableDataSourcesVM) Get() *DataSourcesVM {
	return v.value
}

func (v *NullableDataSourcesVM) Set(val *DataSourcesVM) {
	v.value = val
	v.isSet = true
}

func (v NullableDataSourcesVM) IsSet() bool {
	return v.isSet
}

func (v *NullableDataSourcesVM) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDataSourcesVM(val *DataSourcesVM) *NullableDataSourcesVM {
	return &NullableDataSourcesVM{value: val, isSet: true}
}

func (v NullableDataSourcesVM) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDataSourcesVM) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


