/*
FastReport Cloud

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gofrcloud

import (
	"encoding/json"
)

// checks if the AdminTemplateFolderCreateVM type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AdminTemplateFolderCreateVM{}

// AdminTemplateFolderCreateVM struct for AdminTemplateFolderCreateVM
type AdminTemplateFolderCreateVM struct {
}

// NewAdminTemplateFolderCreateVM instantiates a new AdminTemplateFolderCreateVM object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAdminTemplateFolderCreateVM() *AdminTemplateFolderCreateVM {
	this := AdminTemplateFolderCreateVM{}
	return &this
}

// NewAdminTemplateFolderCreateVMWithDefaults instantiates a new AdminTemplateFolderCreateVM object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAdminTemplateFolderCreateVMWithDefaults() *AdminTemplateFolderCreateVM {
	this := AdminTemplateFolderCreateVM{}
	return &this
}

func (o AdminTemplateFolderCreateVM) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AdminTemplateFolderCreateVM) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	return toSerialize, nil
}

type NullableAdminTemplateFolderCreateVM struct {
	value *AdminTemplateFolderCreateVM
	isSet bool
}

func (v NullableAdminTemplateFolderCreateVM) Get() *AdminTemplateFolderCreateVM {
	return v.value
}

func (v *NullableAdminTemplateFolderCreateVM) Set(val *AdminTemplateFolderCreateVM) {
	v.value = val
	v.isSet = true
}

func (v NullableAdminTemplateFolderCreateVM) IsSet() bool {
	return v.isSet
}

func (v *NullableAdminTemplateFolderCreateVM) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAdminTemplateFolderCreateVM(val *AdminTemplateFolderCreateVM) *NullableAdminTemplateFolderCreateVM {
	return &NullableAdminTemplateFolderCreateVM{value: val, isSet: true}
}

func (v NullableAdminTemplateFolderCreateVM) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAdminTemplateFolderCreateVM) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


