/*
FastReport Cloud

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gofrcloud

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateDataSourceSubscriptionVM type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateDataSourceSubscriptionVM{}

// UpdateDataSourceSubscriptionVM struct for UpdateDataSourceSubscriptionVM
type UpdateDataSourceSubscriptionVM struct {
	CloudBaseVM
	SubscriptionId string `json:"subscriptionId"`
	T string `json:"$t"`
}

type _UpdateDataSourceSubscriptionVM UpdateDataSourceSubscriptionVM

// NewUpdateDataSourceSubscriptionVM instantiates a new UpdateDataSourceSubscriptionVM object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateDataSourceSubscriptionVM(subscriptionId string, t string) *UpdateDataSourceSubscriptionVM {
	this := UpdateDataSourceSubscriptionVM{}
	this.T = t
	return &this
}

// NewUpdateDataSourceSubscriptionVMWithDefaults instantiates a new UpdateDataSourceSubscriptionVM object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateDataSourceSubscriptionVMWithDefaults() *UpdateDataSourceSubscriptionVM {
	this := UpdateDataSourceSubscriptionVM{}
	return &this
}

// GetSubscriptionId returns the SubscriptionId field value
func (o *UpdateDataSourceSubscriptionVM) GetSubscriptionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SubscriptionId
}

// GetSubscriptionIdOk returns a tuple with the SubscriptionId field value
// and a boolean to check if the value has been set.
func (o *UpdateDataSourceSubscriptionVM) GetSubscriptionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SubscriptionId, true
}

// SetSubscriptionId sets field value
func (o *UpdateDataSourceSubscriptionVM) SetSubscriptionId(v string) {
	o.SubscriptionId = v
}

// GetT returns the T field value
func (o *UpdateDataSourceSubscriptionVM) GetT() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.T
}

// GetTOk returns a tuple with the T field value
// and a boolean to check if the value has been set.
func (o *UpdateDataSourceSubscriptionVM) GetTOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.T, true
}

// SetT sets field value
func (o *UpdateDataSourceSubscriptionVM) SetT(v string) {
	o.T = v
}

func (o UpdateDataSourceSubscriptionVM) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateDataSourceSubscriptionVM) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	serializedCloudBaseVM, errCloudBaseVM := json.Marshal(o.CloudBaseVM)
	if errCloudBaseVM != nil {
		return map[string]interface{}{}, errCloudBaseVM
	}
	errCloudBaseVM = json.Unmarshal([]byte(serializedCloudBaseVM), &toSerialize)
	if errCloudBaseVM != nil {
		return map[string]interface{}{}, errCloudBaseVM
	}
	toSerialize["subscriptionId"] = o.SubscriptionId
	toSerialize["$t"] = o.T
	return toSerialize, nil
}

func (o *UpdateDataSourceSubscriptionVM) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"subscriptionId",
		"$t",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateDataSourceSubscriptionVM := _UpdateDataSourceSubscriptionVM{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateDataSourceSubscriptionVM)

	if err != nil {
		return err
	}

	*o = UpdateDataSourceSubscriptionVM(varUpdateDataSourceSubscriptionVM)

	return err
}

type NullableUpdateDataSourceSubscriptionVM struct {
	value *UpdateDataSourceSubscriptionVM
	isSet bool
}

func (v NullableUpdateDataSourceSubscriptionVM) Get() *UpdateDataSourceSubscriptionVM {
	return v.value
}

func (v *NullableUpdateDataSourceSubscriptionVM) Set(val *UpdateDataSourceSubscriptionVM) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateDataSourceSubscriptionVM) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateDataSourceSubscriptionVM) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateDataSourceSubscriptionVM(val *UpdateDataSourceSubscriptionVM) *NullableUpdateDataSourceSubscriptionVM {
	return &NullableUpdateDataSourceSubscriptionVM{value: val, isSet: true}
}

func (v NullableUpdateDataSourceSubscriptionVM) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateDataSourceSubscriptionVM) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


