/*
FastReport Cloud

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gofrcloud

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GroupPermissionCRUDVM type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GroupPermissionCRUDVM{}

// GroupPermissionCRUDVM struct for GroupPermissionCRUDVM
type GroupPermissionCRUDVM struct {
	CloudBaseVM
	Create *GroupCreate `json:"create,omitempty"`
	Delete *GroupDelete `json:"delete,omitempty"`
	Execute *GroupExecute `json:"execute,omitempty"`
	Get *GroupGet `json:"get,omitempty"`
	Update *GroupUpdate `json:"update,omitempty"`
	Administrate *GroupAdministrate `json:"administrate,omitempty"`
	T string `json:"$t"`
}

type _GroupPermissionCRUDVM GroupPermissionCRUDVM

// NewGroupPermissionCRUDVM instantiates a new GroupPermissionCRUDVM object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGroupPermissionCRUDVM(t string) *GroupPermissionCRUDVM {
	this := GroupPermissionCRUDVM{}
	this.T = t
	return &this
}

// NewGroupPermissionCRUDVMWithDefaults instantiates a new GroupPermissionCRUDVM object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGroupPermissionCRUDVMWithDefaults() *GroupPermissionCRUDVM {
	this := GroupPermissionCRUDVM{}
	return &this
}

// GetCreate returns the Create field value if set, zero value otherwise.
func (o *GroupPermissionCRUDVM) GetCreate() GroupCreate {
	if o == nil || IsNil(o.Create) {
		var ret GroupCreate
		return ret
	}
	return *o.Create
}

// GetCreateOk returns a tuple with the Create field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupPermissionCRUDVM) GetCreateOk() (*GroupCreate, bool) {
	if o == nil || IsNil(o.Create) {
		return nil, false
	}
	return o.Create, true
}

// HasCreate returns a boolean if a field has been set.
func (o *GroupPermissionCRUDVM) HasCreate() bool {
	if o != nil && !IsNil(o.Create) {
		return true
	}

	return false
}

// SetCreate gets a reference to the given GroupCreate and assigns it to the Create field.
func (o *GroupPermissionCRUDVM) SetCreate(v GroupCreate) {
	o.Create = &v
}

// GetDelete returns the Delete field value if set, zero value otherwise.
func (o *GroupPermissionCRUDVM) GetDelete() GroupDelete {
	if o == nil || IsNil(o.Delete) {
		var ret GroupDelete
		return ret
	}
	return *o.Delete
}

// GetDeleteOk returns a tuple with the Delete field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupPermissionCRUDVM) GetDeleteOk() (*GroupDelete, bool) {
	if o == nil || IsNil(o.Delete) {
		return nil, false
	}
	return o.Delete, true
}

// HasDelete returns a boolean if a field has been set.
func (o *GroupPermissionCRUDVM) HasDelete() bool {
	if o != nil && !IsNil(o.Delete) {
		return true
	}

	return false
}

// SetDelete gets a reference to the given GroupDelete and assigns it to the Delete field.
func (o *GroupPermissionCRUDVM) SetDelete(v GroupDelete) {
	o.Delete = &v
}

// GetExecute returns the Execute field value if set, zero value otherwise.
func (o *GroupPermissionCRUDVM) GetExecute() GroupExecute {
	if o == nil || IsNil(o.Execute) {
		var ret GroupExecute
		return ret
	}
	return *o.Execute
}

// GetExecuteOk returns a tuple with the Execute field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupPermissionCRUDVM) GetExecuteOk() (*GroupExecute, bool) {
	if o == nil || IsNil(o.Execute) {
		return nil, false
	}
	return o.Execute, true
}

// HasExecute returns a boolean if a field has been set.
func (o *GroupPermissionCRUDVM) HasExecute() bool {
	if o != nil && !IsNil(o.Execute) {
		return true
	}

	return false
}

// SetExecute gets a reference to the given GroupExecute and assigns it to the Execute field.
func (o *GroupPermissionCRUDVM) SetExecute(v GroupExecute) {
	o.Execute = &v
}

// GetGet returns the Get field value if set, zero value otherwise.
func (o *GroupPermissionCRUDVM) GetGet() GroupGet {
	if o == nil || IsNil(o.Get) {
		var ret GroupGet
		return ret
	}
	return *o.Get
}

// GetGetOk returns a tuple with the Get field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupPermissionCRUDVM) GetGetOk() (*GroupGet, bool) {
	if o == nil || IsNil(o.Get) {
		return nil, false
	}
	return o.Get, true
}

// HasGet returns a boolean if a field has been set.
func (o *GroupPermissionCRUDVM) HasGet() bool {
	if o != nil && !IsNil(o.Get) {
		return true
	}

	return false
}

// SetGet gets a reference to the given GroupGet and assigns it to the Get field.
func (o *GroupPermissionCRUDVM) SetGet(v GroupGet) {
	o.Get = &v
}

// GetUpdate returns the Update field value if set, zero value otherwise.
func (o *GroupPermissionCRUDVM) GetUpdate() GroupUpdate {
	if o == nil || IsNil(o.Update) {
		var ret GroupUpdate
		return ret
	}
	return *o.Update
}

// GetUpdateOk returns a tuple with the Update field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupPermissionCRUDVM) GetUpdateOk() (*GroupUpdate, bool) {
	if o == nil || IsNil(o.Update) {
		return nil, false
	}
	return o.Update, true
}

// HasUpdate returns a boolean if a field has been set.
func (o *GroupPermissionCRUDVM) HasUpdate() bool {
	if o != nil && !IsNil(o.Update) {
		return true
	}

	return false
}

// SetUpdate gets a reference to the given GroupUpdate and assigns it to the Update field.
func (o *GroupPermissionCRUDVM) SetUpdate(v GroupUpdate) {
	o.Update = &v
}

// GetAdministrate returns the Administrate field value if set, zero value otherwise.
func (o *GroupPermissionCRUDVM) GetAdministrate() GroupAdministrate {
	if o == nil || IsNil(o.Administrate) {
		var ret GroupAdministrate
		return ret
	}
	return *o.Administrate
}

// GetAdministrateOk returns a tuple with the Administrate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupPermissionCRUDVM) GetAdministrateOk() (*GroupAdministrate, bool) {
	if o == nil || IsNil(o.Administrate) {
		return nil, false
	}
	return o.Administrate, true
}

// HasAdministrate returns a boolean if a field has been set.
func (o *GroupPermissionCRUDVM) HasAdministrate() bool {
	if o != nil && !IsNil(o.Administrate) {
		return true
	}

	return false
}

// SetAdministrate gets a reference to the given GroupAdministrate and assigns it to the Administrate field.
func (o *GroupPermissionCRUDVM) SetAdministrate(v GroupAdministrate) {
	o.Administrate = &v
}

// GetT returns the T field value
func (o *GroupPermissionCRUDVM) GetT() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.T
}

// GetTOk returns a tuple with the T field value
// and a boolean to check if the value has been set.
func (o *GroupPermissionCRUDVM) GetTOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.T, true
}

// SetT sets field value
func (o *GroupPermissionCRUDVM) SetT(v string) {
	o.T = v
}

func (o GroupPermissionCRUDVM) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GroupPermissionCRUDVM) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	serializedCloudBaseVM, errCloudBaseVM := json.Marshal(o.CloudBaseVM)
	if errCloudBaseVM != nil {
		return map[string]interface{}{}, errCloudBaseVM
	}
	errCloudBaseVM = json.Unmarshal([]byte(serializedCloudBaseVM), &toSerialize)
	if errCloudBaseVM != nil {
		return map[string]interface{}{}, errCloudBaseVM
	}
	if !IsNil(o.Create) {
		toSerialize["create"] = o.Create
	}
	if !IsNil(o.Delete) {
		toSerialize["delete"] = o.Delete
	}
	if !IsNil(o.Execute) {
		toSerialize["execute"] = o.Execute
	}
	if !IsNil(o.Get) {
		toSerialize["get"] = o.Get
	}
	if !IsNil(o.Update) {
		toSerialize["update"] = o.Update
	}
	if !IsNil(o.Administrate) {
		toSerialize["administrate"] = o.Administrate
	}
	toSerialize["$t"] = o.T
	return toSerialize, nil
}

func (o *GroupPermissionCRUDVM) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"$t",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGroupPermissionCRUDVM := _GroupPermissionCRUDVM{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGroupPermissionCRUDVM)

	if err != nil {
		return err
	}

	*o = GroupPermissionCRUDVM(varGroupPermissionCRUDVM)

	return err
}

type NullableGroupPermissionCRUDVM struct {
	value *GroupPermissionCRUDVM
	isSet bool
}

func (v NullableGroupPermissionCRUDVM) Get() *GroupPermissionCRUDVM {
	return v.value
}

func (v *NullableGroupPermissionCRUDVM) Set(val *GroupPermissionCRUDVM) {
	v.value = val
	v.isSet = true
}

func (v NullableGroupPermissionCRUDVM) IsSet() bool {
	return v.isSet
}

func (v *NullableGroupPermissionCRUDVM) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGroupPermissionCRUDVM(val *GroupPermissionCRUDVM) *NullableGroupPermissionCRUDVM {
	return &NullableGroupPermissionCRUDVM{value: val, isSet: true}
}

func (v NullableGroupPermissionCRUDVM) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGroupPermissionCRUDVM) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


