/*
FastReport Cloud

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gofrcloud

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateExportTemplateTaskVM type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateExportTemplateTaskVM{}

// UpdateExportTemplateTaskVM struct for UpdateExportTemplateTaskVM
type UpdateExportTemplateTaskVM struct {
	UpdateExportReportTaskVM
	ReportParameters map[string]string `json:"reportParameters,omitempty"`
	T string `json:"$t"`
}

type _UpdateExportTemplateTaskVM UpdateExportTemplateTaskVM

// NewUpdateExportTemplateTaskVM instantiates a new UpdateExportTemplateTaskVM object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateExportTemplateTaskVM(t string) *UpdateExportTemplateTaskVM {
	this := UpdateExportTemplateTaskVM{}
	this.T = t
	return &this
}

// NewUpdateExportTemplateTaskVMWithDefaults instantiates a new UpdateExportTemplateTaskVM object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateExportTemplateTaskVMWithDefaults() *UpdateExportTemplateTaskVM {
	this := UpdateExportTemplateTaskVM{}
	return &this
}

// GetReportParameters returns the ReportParameters field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateExportTemplateTaskVM) GetReportParameters() map[string]string {
	if o == nil {
		var ret map[string]string
		return ret
	}
	return o.ReportParameters
}

// GetReportParametersOk returns a tuple with the ReportParameters field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateExportTemplateTaskVM) GetReportParametersOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.ReportParameters) {
		return nil, false
	}
	return &o.ReportParameters, true
}

// HasReportParameters returns a boolean if a field has been set.
func (o *UpdateExportTemplateTaskVM) HasReportParameters() bool {
	if o != nil && IsNil(o.ReportParameters) {
		return true
	}

	return false
}

// SetReportParameters gets a reference to the given map[string]string and assigns it to the ReportParameters field.
func (o *UpdateExportTemplateTaskVM) SetReportParameters(v map[string]string) {
	o.ReportParameters = v
}

// GetT returns the T field value
func (o *UpdateExportTemplateTaskVM) GetT() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.T
}

// GetTOk returns a tuple with the T field value
// and a boolean to check if the value has been set.
func (o *UpdateExportTemplateTaskVM) GetTOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.T, true
}

// SetT sets field value
func (o *UpdateExportTemplateTaskVM) SetT(v string) {
	o.T = v
}

func (o UpdateExportTemplateTaskVM) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateExportTemplateTaskVM) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	serializedUpdateExportReportTaskVM, errUpdateExportReportTaskVM := json.Marshal(o.UpdateExportReportTaskVM)
	if errUpdateExportReportTaskVM != nil {
		return map[string]interface{}{}, errUpdateExportReportTaskVM
	}
	errUpdateExportReportTaskVM = json.Unmarshal([]byte(serializedUpdateExportReportTaskVM), &toSerialize)
	if errUpdateExportReportTaskVM != nil {
		return map[string]interface{}{}, errUpdateExportReportTaskVM
	}
	if o.ReportParameters != nil {
		toSerialize["reportParameters"] = o.ReportParameters
	}
	toSerialize["$t"] = o.T
	return toSerialize, nil
}

func (o *UpdateExportTemplateTaskVM) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"$t",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateExportTemplateTaskVM := _UpdateExportTemplateTaskVM{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateExportTemplateTaskVM)

	if err != nil {
		return err
	}

	*o = UpdateExportTemplateTaskVM(varUpdateExportTemplateTaskVM)

	return err
}

type NullableUpdateExportTemplateTaskVM struct {
	value *UpdateExportTemplateTaskVM
	isSet bool
}

func (v NullableUpdateExportTemplateTaskVM) Get() *UpdateExportTemplateTaskVM {
	return v.value
}

func (v *NullableUpdateExportTemplateTaskVM) Set(val *UpdateExportTemplateTaskVM) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateExportTemplateTaskVM) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateExportTemplateTaskVM) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateExportTemplateTaskVM(val *UpdateExportTemplateTaskVM) *NullableUpdateExportTemplateTaskVM {
	return &NullableUpdateExportTemplateTaskVM{value: val, isSet: true}
}

func (v NullableUpdateExportTemplateTaskVM) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateExportTemplateTaskVM) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


