/*
FastReport Cloud

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gofrcloud

import (
	"encoding/json"
)

// checks if the ReportCreateVM type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ReportCreateVM{}

// ReportCreateVM struct for ReportCreateVM
type ReportCreateVM struct {
	TemplateId NullableString `json:"templateId,omitempty"`
}

// NewReportCreateVM instantiates a new ReportCreateVM object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReportCreateVM() *ReportCreateVM {
	this := ReportCreateVM{}
	return &this
}

// NewReportCreateVMWithDefaults instantiates a new ReportCreateVM object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReportCreateVMWithDefaults() *ReportCreateVM {
	this := ReportCreateVM{}
	return &this
}

// GetTemplateId returns the TemplateId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ReportCreateVM) GetTemplateId() string {
	if o == nil || IsNil(o.TemplateId.Get()) {
		var ret string
		return ret
	}
	return *o.TemplateId.Get()
}

// GetTemplateIdOk returns a tuple with the TemplateId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ReportCreateVM) GetTemplateIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TemplateId.Get(), o.TemplateId.IsSet()
}

// HasTemplateId returns a boolean if a field has been set.
func (o *ReportCreateVM) HasTemplateId() bool {
	if o != nil && o.TemplateId.IsSet() {
		return true
	}

	return false
}

// SetTemplateId gets a reference to the given NullableString and assigns it to the TemplateId field.
func (o *ReportCreateVM) SetTemplateId(v string) {
	o.TemplateId.Set(&v)
}
// SetTemplateIdNil sets the value for TemplateId to be an explicit nil
func (o *ReportCreateVM) SetTemplateIdNil() {
	o.TemplateId.Set(nil)
}

// UnsetTemplateId ensures that no value is present for TemplateId, not even an explicit nil
func (o *ReportCreateVM) UnsetTemplateId() {
	o.TemplateId.Unset()
}

func (o ReportCreateVM) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ReportCreateVM) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.TemplateId.IsSet() {
		toSerialize["templateId"] = o.TemplateId.Get()
	}
	return toSerialize, nil
}

type NullableReportCreateVM struct {
	value *ReportCreateVM
	isSet bool
}

func (v NullableReportCreateVM) Get() *ReportCreateVM {
	return v.value
}

func (v *NullableReportCreateVM) Set(val *ReportCreateVM) {
	v.value = val
	v.isSet = true
}

func (v NullableReportCreateVM) IsSet() bool {
	return v.isSet
}

func (v *NullableReportCreateVM) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReportCreateVM(val *ReportCreateVM) *NullableReportCreateVM {
	return &NullableReportCreateVM{value: val, isSet: true}
}

func (v NullableReportCreateVM) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReportCreateVM) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


