/*
FastReport Cloud

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gofrcloud

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the FilesVM type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FilesVM{}

// FilesVM struct for FilesVM
type FilesVM struct {
	FilesVMBase
	T string `json:"$t"`
}

type _FilesVM FilesVM

// NewFilesVM instantiates a new FilesVM object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFilesVM(t string) *FilesVM {
	this := FilesVM{}
	this.T = t
	return &this
}

// NewFilesVMWithDefaults instantiates a new FilesVM object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFilesVMWithDefaults() *FilesVM {
	this := FilesVM{}
	return &this
}

// GetT returns the T field value
func (o *FilesVM) GetT() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.T
}

// GetTOk returns a tuple with the T field value
// and a boolean to check if the value has been set.
func (o *FilesVM) GetTOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.T, true
}

// SetT sets field value
func (o *FilesVM) SetT(v string) {
	o.T = v
}

func (o FilesVM) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FilesVM) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	serializedFilesVMBase, errFilesVMBase := json.Marshal(o.FilesVMBase)
	if errFilesVMBase != nil {
		return map[string]interface{}{}, errFilesVMBase
	}
	errFilesVMBase = json.Unmarshal([]byte(serializedFilesVMBase), &toSerialize)
	if errFilesVMBase != nil {
		return map[string]interface{}{}, errFilesVMBase
	}
	toSerialize["$t"] = o.T
	return toSerialize, nil
}

func (o *FilesVM) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"$t",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFilesVM := _FilesVM{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varFilesVM)

	if err != nil {
		return err
	}

	*o = FilesVM(varFilesVM)

	return err
}

type NullableFilesVM struct {
	value *FilesVM
	isSet bool
}

func (v NullableFilesVM) Get() *FilesVM {
	return v.value
}

func (v *NullableFilesVM) Set(val *FilesVM) {
	v.value = val
	v.isSet = true
}

func (v NullableFilesVM) IsSet() bool {
	return v.isSet
}

func (v *NullableFilesVM) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFilesVM(val *FilesVM) *NullableFilesVM {
	return &NullableFilesVM{value: val, isSet: true}
}

func (v NullableFilesVM) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFilesVM) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


